### ISSUE TITLE
Not working on NodeMCU

### ISSUE THREAD

**Issue by fixItFab** [Syberteck/esp8266-Smart-Plug#1]
Hey,

I have a Echo 2nd Gen and already tried a several of libs and implementations but none wants to work.

I tried this with a NodeMCU, but no success :( . First at all, i had to delete the Serial.println in the Switch constructor. The NodeMCU doesn't like to it and reboot when you try to make a Serial.println, before the baud rate of the Serial was set. 

After fixing, i tried to discover the test device, but no device was found by the Echo.

Did you already tested it with a NodeMCU, WeMos D1 mini or a plain ESP8266? 

Here is my log: 

`Sending response to 192.168.178.45
Port : 3962
Response sent !
Got UDP Belkin Request..

Sending response to 192.168.178.102
Port : 50000
Response sent !
Got UDP Belkin Request..

Sending response to 192.168.178.102
Port : 50000
Response sent !
 ########## Responding to setup.xml ... ########

Sending :<?xml version="1.0"?><root><device><deviceType>urn:Belkin:device:controllee:1</deviceType><friendlyName>smart plug</friendlyName><manufacturer>Bel
kin International Inc.</manufacturer><modelName>Socket</modelName><modelNumber>3.1415</modelNumber><modelDescription>Belkin Plugin Socket 1.0</modelDescrip
tion>
<UDN>uuid:Socket-1_0-38323636-4558-4dda-9188-cda0e62ba145-80</UDN><serialNumber>221517K0101769</serialNumber><binaryState>0</binaryState><serviceList><serv
ice><serviceType>urn:Belkin:service:basicevent:1</serviceType><serviceId>urn:Belkin:serviceId:basicevent1</serviceId><controlURL>/upnp/control/basicevent1<
/controlURL><eventSubURL>/upnp/event/basicevent1</eventSubURL><SCPDURL>/eventservice.xml</SCPDURL></service></serviceList></device></root>

Got UDP Belkin Request..

Sending response to 192.168.178.102
Port : 50000
Response sent !
Got UDP Belkin Request..`

**Comment by Syberteck** [comment]
I only have a Sonoff S20 device, which is a esp8266. It works on a esp8266. This is for esp8266 only. Sorry.
